env:
  browser: true
root: true
extends:
  - airbnb
  - prettier
plugins:
  - prettier
rules:
  prettier/prettier: error
  valid-jsdoc: error
  no-underscore-dangle: 0
  import/extensions:
    - 'off'
    - always
  class-methods-use-this: 0
overrides:
  files:
    - __tests__/**
  rules:
    import/no-extraneous-dependencies:
      - error
      - devDependencies: true
